# Generated by Django 2.1.2 on 2018-11-29 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commom', '0004_auto_20181129_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protocolos',
            name='method_class',
        ),
    ]
