# Generated by Django 2.1.2 on 2018-11-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commom', '0005_remove_protocolos_method_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolos',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
