# Generated by Django 2.1.2 on 2018-11-29 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commom', '0006_auto_20181129_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolos',
            name='method_class',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='commom.CategoriasProtocolos'),
        ),
    ]
