# Generated by Django 2.1.3 on 2018-12-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commom', '0008_auto_20181129_1219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='protocolos',
            options={'verbose_name_plural': 'Protocolos'},
        ),
        migrations.AlterField(
            model_name='protocolos',
            name='file',
            field=models.FileField(upload_to='protocolos'),
        ),
    ]
