# Generated by Django 2.1.3 on 2018-12-13 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avisos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Aviso', max_length=30)),
                ('aviso', models.CharField(default='AVISO', max_length=2000)),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_final', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Avisos',
            },
        ),
        migrations.CreateModel(
            name='CategoriasProtocolos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(default='Extração', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Protocolos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_name', models.CharField(default='Método', max_length=20)),
                ('file', models.FileField(upload_to='protocolos')),
                ('method_class', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='commom.CategoriasProtocolos')),
            ],
            options={
                'verbose_name_plural': 'Protocolos',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lates', models.CharField(default='http://lattes.cnpq.br/', max_length=300)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='avisos',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='commom.UserProfile'),
        ),
    ]
