# Generated by Django 2.1.3 on 2018-12-13 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='lates',
        ),
    ]
