# Generated by Django 2.1.3 on 2018-12-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commom', '0002_remove_userprofile_lates'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='lates',
            field=models.CharField(default='http://lattes.cnpq.br/', max_length=300),
        ),
    ]
