# Generated by Django 2.1.3 on 2018-12-13 17:38

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commom', '0003_userprofile_lates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpEquip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_name', models.CharField(default='HS-SPME', max_length=50)),
                ('equip', models.CharField(default='GC/MS', max_length=300)),
                ('location', models.CharField(default='Fitoquímica', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Equipamentos',
            },
        ),
        migrations.CreateModel(
            name='ExpSupplies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_name', models.CharField(default='HS-SPME', max_length=50)),
                ('supplie_name', models.CharField(default='recurso', max_length=50)),
                ('supplie_amount', models.PositiveIntegerField(default=1)),
                ('supplie_measurement', models.CharField(default='X', max_length=10)),
                ('disponibilidade', models.PositiveSmallIntegerField(choices=[(1, 'Disponível'), (2, 'Não Disponível')], default=2)),
            ],
            options={
                'verbose_name_plural': 'Materiais',
            },
        ),
        migrations.CreateModel(
            name='ExpToDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_name', models.CharField(default='HS-SPME', max_length=50)),
                ('note', models.CharField(default='A Fazer', max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Afazeres',
            },
        ),
        migrations.CreateModel(
            name='LastSeen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Visitas',
            },
        ),
        migrations.CreateModel(
            name='ProjectDocs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, '.docx'), (2, '.xlsx'), (3, '.pdf'), (4, 'outros')], default=1)),
                ('file', models.FileField(upload_to=accounts.models.user_directory_path)),
            ],
            options={
                'verbose_name_plural': 'Documentos',
            },
        ),
        migrations.CreateModel(
            name='ProjectFacilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility2', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('coordinator', models.PositiveSmallIntegerField(choices=[(1, 'Não'), (2, 'Sim')])),
            ],
            options={
                'verbose_name_plural': 'Membros de Projetos',
            },
        ),
        migrations.CreateModel(
            name='UserExperiments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Experimento', max_length=100)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='commom.UserProfile')),
            ],
            options={
                'verbose_name_plural': 'Experimentos',
            },
        ),
        migrations.CreateModel(
            name='UserProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Projeto', max_length=200)),
                ('description', models.CharField(default='descrição', max_length=2000)),
                ('current_state', models.PositiveSmallIntegerField(choices=[(1, 'Concluido'), (2, 'Em Andamento'), (3, 'Desativado')], default=2)),
                ('date_begin', models.DateField(blank=True, null=True)),
                ('date_final', models.DateField(blank=True, null=True)),
                ('research_inst', models.CharField(default='Instituição de Pesquisa', max_length=30)),
                ('facility', models.CharField(default='Departamento', max_length=30)),
                ('nivel', models.PositiveSmallIntegerField(choices=[(1, 'Iniciação Científica'), (2, 'Mestrado'), (3, 'Doutorado'), (4, 'Pós-Doc.')])),
                ('students', models.PositiveSmallIntegerField(default=0)),
                ('user', models.ForeignKey(default='guibax', on_delete=django.db.models.deletion.CASCADE, to='commom.UserProfile')),
            ],
            options={
                'verbose_name_plural': 'Projetos',
            },
        ),
        migrations.AddField(
            model_name='projectmember',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProjects'),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='user',
            field=models.ForeignKey(default='guibax', on_delete=django.db.models.deletion.CASCADE, to='commom.UserProfile'),
        ),
        migrations.AddField(
            model_name='projectfacilities',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProjects'),
        ),
        migrations.AddField(
            model_name='projectdocs',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProjects'),
        ),
        migrations.AddField(
            model_name='projectdocs',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exptodo',
            name='exp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserExperiments'),
        ),
        migrations.AddField(
            model_name='expsupplies',
            name='exp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserExperiments'),
        ),
        migrations.AddField(
            model_name='expequip',
            name='exp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserExperiments'),
        ),
    ]
