# Generated by Django 2.1.3 on 2018-12-13 17:46

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20181213_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDocs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, '.docx'), (2, '.xlsx'), (3, '.pdf'), (4, 'outros')], default=1)),
                ('file', models.FileField(upload_to=accounts.models.user_directory_path)),
                ('project', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProjects')),
                ('user', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Documentos',
            },
        ),
    ]
