# Generated by Django 2.1.2 on 2018-12-18 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commom', '0003_userprofile_lates'),
        ('accounts', '0004_auto_20181218_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpEquip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_name', models.CharField(default='HS-SPME', max_length=50)),
                ('equip', models.CharField(default='GC/MS', max_length=300)),
                ('location', models.CharField(default='Fitoquímica', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Equipamentos',
            },
        ),
        migrations.CreateModel(
            name='ExpSupplies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_name', models.CharField(default='HS-SPME', max_length=50)),
                ('supplie_name', models.CharField(default='recurso', max_length=50)),
                ('supplie_amount', models.PositiveIntegerField(default=1)),
                ('supplie_measurement', models.CharField(default='X', max_length=10)),
                ('disponibilidade', models.PositiveSmallIntegerField(choices=[(1, 'Disponível'), (2, 'Não Disponível')], default=2)),
            ],
            options={
                'verbose_name_plural': 'Materiais',
            },
        ),
        migrations.CreateModel(
            name='ExpToDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_name', models.CharField(default='HS-SPME', max_length=50)),
                ('note', models.CharField(default='A Fazer', max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Afazeres',
            },
        ),
        migrations.CreateModel(
            name='UserExperiments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Experimento', max_length=100)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='commom.UserProfile')),
            ],
            options={
                'verbose_name_plural': 'Experimentos',
            },
        ),
        migrations.AddField(
            model_name='exptodo',
            name='exp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserExperiments'),
        ),
        migrations.AddField(
            model_name='expsupplies',
            name='exp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserExperiments'),
        ),
        migrations.AddField(
            model_name='expequip',
            name='exp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserExperiments'),
        ),
    ]
