# Generated by Django 2.1.3 on 2018-11-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ars', models.IntegerField(default=0)),
                ('ars_p', models.IntegerField(default=0)),
                ('h2', models.IntegerField(default=0)),
                ('h2_p', models.IntegerField(default=0)),
                ('he', models.IntegerField(default=0)),
                ('he_p', models.IntegerField(default=0)),
                ('ver_name', models.CharField(default='None', max_length=100)),
                ('ver_date', models.CharField(default='None', max_length=12)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Gases',
            },
        ),
    ]
