# Generated by Django 2.1.3 on 2018-11-23 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cromatografia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gas',
            name='created_at',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
