# Generated by Django 2.1.3 on 2018-11-23 16:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cromatografia', '0004_auto_20181123_1456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gas',
            options={'get_latest_by': 'created_at', 'verbose_name_plural': 'Gases'},
        ),
        migrations.AddField(
            model_name='gas',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
